#!/bin/bash
lb config noauto \
    --architectures amd64 \
    --mode debian \
    --distribution noble \
    --mirror-bootstrap "http://us.archive.ubuntu.com/ubuntu/" \
    --mirror-binary "http://us.archive.ubuntu.com/ubuntu/" \
    --iso-application "OmniLinux" \
    --iso-publisher "OmniLinux Project" \
    --iso-volume "OmniLinux 1.0 LTS" \
    --bootappend-live "boot=live components quiet splash" \
    --linux-packages "linux-image-generic" \
    --initramfs "initramfs-tools" \
    --system live \
    --source false \
    --binary-images iso-hybrid