#!/bin/bash
# Generate OmniLinux GRUB theme assets
# Run this script to create theme images from scratch or use provided templates

set -e

THEME_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ASSETS_DIR="$THEME_DIR"

echo "Generating OmniLinux GRUB theme assets..."

# Create background using ImageMagick if available
if command -v convert &> /dev/null; then
    convert -size 1920x1080 \
        -define gradient:angle=135 \
        gradient:'#0D1117-#1a1f2e' \
        -fill '#3D7EFF' -draw "circle 960,540 1000,540" \
        "$ASSETS_DIR/background.png"
    echo "Created background.png"
else
    # Create a simple solid color PNG as fallback
    echo "ImageMagick not found. Creating placeholder..."
    # Use base64 encoded minimal PNG
    echo "iVBORw0KGgoAAAANSUhEUgAAAgAAAAIACAYAAAD0eNT6AAAABHNCSVQICAgIfAhkiAAAAAlwSFlzAAAOxAAADsQBlSsOGwAAABl0RVh0U29mdHdhcmUAd3d3Lmlua3NjYXBlLm9yZ5vuPBoAAAKoSURBVHic7d1BbttAFIDheSQlUiJl4gW4A12BK3AFbkAF7sAFWIYrUF4FkiIpinxn2PG0E0dKlEiKfL4Z6/l8qVQqIYQK/h8BQoAABBAgQAAACBAgQAAAAgQICAAAAAECBAAAAAgQIEAAAggQAACAAAECEgQIEIAAAgQIECAgQYAAAQIECBAgQAAABAgQIECAAAECBAgQIECAAAECBAgQIECAAAECBAgQIECAAAECBAgQIECAAAECBAgQIECAAAECBAgQIECAAAECBAgQIECAAAECBAgQIECAAAECBAgQIECAAAECBAgQIECAAAECBAgQIECAAAECBAgQIECAAAECBAgQIECAAAECBAgQIECAAAECBAgQIECAAAECBAgQIECAAAECBAgQIECAAAECBAgQIECAAAECBAgQIECAAAECBAgQIECAAAECBAgQIECAAAECBAgQIECAAAECBAgQIECAAAECBAgQIECAAAECBAgQIECAAAECBAgQIECAAAECBAgQIECAAAECBAgQIECAAAECBAgQIECAAAECBAgQIECAAAECBAgQIECAAAECBAgQIECAAAECBAgQIECAAAECBAgQIECAAAECBAgQIECAAAECBAgQIECAAAECBAgQIECAAAECBAgQIECAAAECBAgQIECAAAECBAgQIECAAAECBAgQIECAAAECBAgQIECAAAECBAgQIECAAAECBAgQIECAAAECBAgQIECAAAECBAgQIECAAAECBAgQIECAAAECBAgQIECAAAECBAgQIECAAAECBAgQIECAAAECBAgQIECAAAECBAgQIECAAAECBAgQIECAAAECBAgQIECAAAECBAgQIECAAAECBAgQIECAAAECBAgQIECAAAECBAgQIECAAAECBAgQIECAAAECBAgQIECAAAECBAgQIECAAAECBAgQIECAAAECBAgQIECAAAECBAgQIECAAAECBAgQIECAAAECBAgQIECAAAECBAgQIECAAAECBAgQIECAAAECBAgQIECAAAECBAgQIECAAAECBAgQIECAAAECBAgQIECAAAECBAgQIECAAAECBAgQIECAAAECBAgQIECAAAECBAgQIECAAAECBAgQIECAAAECBAgQIECAAAECBAgQIECAAAECBAgQIECAAAECBAgQIECAAAECBAgQIECAAAECBAgQIECAAAECBAgQIECAAAECBAgQIECAAAECBAgQIMCvgK1kG/2d2l4wAAAAAElFTkSuQmCC" | base64 -d > "$ASSETS_DIR/background.png"
fi

# Create logo placeholder
if command -v convert &> /dev/null; then
    convert -size 300x300 xc:transparent \
        -fill '#3D7EFF' -draw "roundrectangle 20,20 280,280 30,30" \
        -fill white -gravity center \
        -pointsize 48 -annotate 0 "OmniLinux" \
        "$ASSETS_DIR/omnilinux-white.png"
    echo "Created omnilinux-white.png"
fi

echo "GRUB theme assets generation complete!"
echo "Copy these files to your live-build config:"
echo "  cp -r $ASSETS_DIR/* config/includes.chroot/usr/share/grub/themes/"