name: OmniLinux Build
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Install archiso
        run: |
          sudo apt-get update
          sudo apt-get install -y git make
        
      - name: Build with archiso
        run: |
          cd iso-builder
          sudo make build
          
      - name: Upload ISO
        uses: actions/upload-artifact@v4
        with:
          name: OmniLinux-ISO
          path: iso-builder/*.iso