name: img
on: push
jobs:
  x:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: sudo apt-get update && sudo apt-get install -y live-build
      - run: sudo rm -rf auto chroot live-image-*.iso
      - run: sudo mkdir -p auto
      - run: sudo lb config --mode debian --distribution noble --mirror-bootstrap http://archive.ubuntu.com/ubuntu/ --mirror-binary http://archive.ubuntu.com/ubuntu/ --binary-images iso-hybrid
      - run: sudo lb bootstrap
      - run: sudo lb chroot
      - run: sudo lb build
      - uses: actions/upload-artifact@v4
        with:
          name: iso
          path: live-image-*.iso