name: OmniLinux ISO Build
on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build-iso:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Show environment
        run: |
          echo "GitHub Action runner working!"
          whoami
      
      - name: Upload artifact test
        run: echo "test" > test.txt
      
      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: test
          path: test.txt